language: c

compiler: gcc

dist: xenial

install:
- unset CC
- sudo systemctl enable mysql
- sudo service mysql start
- sudo -E apt update
- sudo -E apt -yq install texinfo lzip help2man libtool-bin
- wget -q http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0-rc2.tar.xz
- tar xf crosstool-ng-1.24.0-rc2.tar.xz
- cd crosstool-ng-1.24.0-rc2
- "./configure"
- make && sudo make install
- cd ..

script:
- cd aarch64-xtool
- ct-ng build

after_success:
- cd ~/x-tools/
- tar cfJ aarch64-linux-android.tar.xz aarch64-linux-android
- mv aarch64-linux-android.tar.xz /home/travis/build/Hubedge/aarch64-linux-android/aarch64-linux-android.tar.xz

deploy:
  provider: releases
  api_key:
    secure: nxhj9G1qlHc5kJg6vcMSs6EuTRMYlaXSBUWRddXwO410II5b2ap2QpT9ztn9qyVVlWbNy554voz6epIFO6Yl9RW1aTwd9fjeXFESsdy2mzgXrFc42zg/1Mn2yB9ANDCh/NnBnB3V3ltL22AtomXOlCT/5/ga6I29+T30evokk/vfhAqwGQy2/umh0JcBU6jN1k16yN/47STUfQABodxMtFIM73EFrzEOiZFdjhtKN1/YPQCgjeSWZRh9VH3LYSRUVda0cwoeiyxJhmX7wMGuhSjMf95A4LL5OT/LbM4pc5pyjS95ShQssNaHvNXyyOPMfc2b8SWsFbLL1uX8bHMtOoW5xmFfn9SA7gN/Ji/+HMk7NjANcb2pgaaNjL8qnZPOOZeFk6Qmhj6ETbiymMKM56rxC2Quvl9M4n+BKSIn2pvBNg841G5SIKycZmKlpWCo+zYy34hDRqpB/inKzN2S2dVwvZG8idxITsxIFdYh4aXE4IHvmk/aXrc1gevx6J9atiOjhw0BvIo96cx5d6HqhqdsY0k5PBfol7HHuwCCOceEAYc8OFV5T+da1wwCXRk8seXeDRuFetT1zjGXsx4az5R9OMC4yqwvnbdwuoYreckX1IZQ3uavQf8CY49LgPdnx2jbRmQaoVWB5Gw+tq901L1o+jk+866JxDt3Qc2tHw0=
  skip_cleanup: true
  on:
    tags: true
